version: "3.5"

services:
    nginx-spa:
        build:
            context: "."
            args:
                ASSEMBLY: "production"
        image: frontautodocker/front
        expose:
            - "80"
        container_name: frontautodocker-front

networks:
    frontend:
        name: frontautodocker-front
